language: julia
julia:
    - 0.4
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Benchmarks"); Pkg.test("Benchmarks"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("Benchmarks")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
